### ISSUE TITLE
"Top of Page" link in template footer bug

### ISSUE THREAD

**Issue by isabela-pf** [Iota-School/notebooks-for-all#11]
## Problem and context

This issue comes from our user testing round 1: navigation. We ran this round of tests with a notebook that uses the [Space Telescope style guides' example tutorial](https://github.com/spacetelescope/style-guides/blob/master/templates/example_notebook.ipynb) which includes elements to be used in every public STScI notebook. One of the elements this template provides is a [footer](https://github.com/spacetelescope/style-guides/blob/master/guides/jupyter-notebooks.md#footer), which includes a "Top of Page" link for easy navigation. 

While few participants used this link to navigate, some who did noted that the link was "broken." In trying to reproduce it myself, I found that while the link is accurate, clickable (participants who tried were able to interact with it), and will visually scroll a user back to the top, it doesn't seem to move [keyboard focus](https://developer.mozilla.org/en-US/docs/Web/Accessibility/Understanding_WCAG/Keyboard). For users relying on focus to give them feedback on where they are on the page, this means the link does not work because their point of reference has not moved.

## Possible solutions

There is only one solution for this from a user experience perspective: the link needs to change the keyboard focus to an element at the top of the page. In terms of implementation, I would imagine this is linking to the top cell. There may be a more standard approach that I am not aware of at the time of writing this.

## Acceptance criteria

- Merge a PR that allows the "Top of page" link to move keyboard focus to the top of the page. This fix should be tested with a screen reader.

## Tasks to complete

- [ ] Explore for standard methods of changing focus in top of page links
- [ ] Make code changes where needed (probably to the template)
- [ ] Get work merged
