### ISSUE TITLE
Vertical scroll jumping when adjusting browser zoom in rendered notebooks

### ISSUE THREAD

**Issue by isabela-pf** [Iota-School/notebooks-for-all#17]
## Problem and context

This issue comes from our user testing round 1: navigation. When completing different tasks, participants who rely on browser zoom changed the percentage zoom throughout the task. For example, skimming through the notebook could happen at 200% zoom while reading a specific cell could happen at 400% zoom. When navigating through the notebook, the constant zooming in and out makes the vertical scroll placement jump around. Participants who rely on zoom have to scroll constantly back and forth to keep the desired content in the viewport. While this did not prevent participants from completing any task, it was unpleasant enough to comment on (and honestly jarring to watch as an observer).

## Possible solutions

The desired user experience is to have some portion of what is currently in the viewport stay in view no matter how browser zoom is adjusted. Functionally, this sounds somewhat like assigning a certain part of the viewport as an anchor for zoom to ripple out from.

In practice, I'm uncertain how we want to solve it. This will require further exploration, mostly around how this is handled in other document-centered interfaces. I suspect this may not be an easy solve because I've experienced this same issue on other platforms as well. 

## Acceptance criteria

Because I have many questions remaining about this feedback, I think this issue can be closed when we

- Determine what next steps we want to take on jumpy scroll on this project

## Tasks to complete

- [ ] Do competitive analysis of scroll anchoring behaviors in other document-centric interfaces
- [ ] Investigate implementation options for anchoring behaviors
- [ ] Reach agreement about what/if we want to fix and where those changes need to be made
- [ ] (tentative) Make code changes where needed
- [ ] (tentative) Get work merged
