### ISSUE TITLE
Move Metadata to the top

### ISSUE THREAD

**Issue by Jenneh** [Iota-School/notebooks-for-all#21]
## Problem and context

When first opening the page, it is unclear who has produced the page and what ethos it has.

## Possible solutions

Move metadata up in the template, or making sure it’s available other than at the end/footer.

## Tasks to complete

- [ ] Add a metadata area to the top of the page
- [ ] first created
- [ ] last updated
- [ ] author
- [ ] Space Telescope (with link)
- [ ] Link to notebook source
- [ ] etc.

**Comment by tonyfast** [comment]
ive been wrestling with where the metadata goes. some of it should go in `meta` tags, and that would only effect the search experience. so far, most of our effort has been on the contents of the notebook and we've been modifying the `main` contents of the document. 

i recently read in [how to section your html](https://css-tricks.com/how-to-section-your-html/#aa-what-goes-inside-headers) that metadata information goes in the `header`. there are probably a bunch of best practices to consume before knowing how to implement this.

**Comment by tonyfast** [comment]
currently, the authors are responsible for putting their authorship information in the document. there is an author's key defined in the notebook metadata we could use to structure this information further. https://github.com/jupyter/nbformat/blob/main/nbformat/v4/nbformat.v4.5.schema.json#L64
