### ISSUE TITLE
Notebook Tutorial Link

### ISSUE THREAD

**Issue by Jenneh** [Iota-School/notebooks-for-all#22]
## Problem and context

Some novice users want to access help when first learning to use a notebook. 

## Possible solutions

Add a link to a help file of some sort. That way people who need it can use it and others easily skip by it.

## Tasks to complete

- [ ] This help should be written in an accessible way
- [ ] Link to notebook tutorial
- [ ] The link should be easy to skip past
- [ ] List specialized shortcuts for notebooks or special screen reader features, list it in the help doc. Example: progress indicator may speak the word loading

**Comment by tonyfast** [comment]
what kind of help information would they like? do they need help knowing how to navigate? definitions of the design system? should we have a single document that describes navigating notebooks rendered by `nbconvert`?
