### ISSUE TITLE
Automatically add link to rendered notebook source

### ISSUE THREAD

**Issue by isabela-pf** [Iota-School/notebooks-for-all#8]
## Problem and context

This issue comes from our user testing round 1: navigation. Multiple test participants either asked questions about the source of rendered notebooks or replied that they would want to be in an editable version of the notebook in order to complete a task to their liking. While these source notebooks are public, there is no way for users to navigate or be aware of the source from its rendered form unless an author decides to add it. Because it was frequently asked to complete tasks like
- Participants' day-to-day work
- Participants' past expectations of notebooks
- Verifying the content of a notebook and its outputs
- Verifying a variety of completed tasks. Several times when participants were asked if they were confident in their answer, they would reply that they wouldn't be very confident without running the notebook themselves

this feature seems like a requirement. With the frequency and range of tasks where participants requested or searched for the source notebook, we need to provide a clear, consistent, and not-author-reliant method of linking a rendered and source notebook.

### Ways we might want to add the link

- Add an autogenerated link to the source where the notebook is converted from.
- Update the notebook authoring template to include a placeholder for the source link and require it upon review. (This would require us changing all past notebooks manually, rather than re-converting them automatically).
- Or some other clever idea you all have!

### Where the link might go

- In an autogenerated cell at the beginning or end of the document. It would probably benefit from some kind of labeling so it appears as a special link that is not at the same level as the rest of the content.
- In a new header or footer area outside the document, but on the same page.
- As a link in the document title.
- As a link appended to the document title.
- Your new idea here!

## Acceptance criteria

This issue can be closed when we 
- Merge a PR that adds the infrastructure for a source link to the desired upstream repo

## Tasks to complete

- [ ] Reach agreement about what linking method we want to pursue and where those changes need to be made
- [ ] Propose visual designs (if needed)
- [ ] Make code changes where needed
- [ ] Get work merged

**Comment by tonyfast** [comment]
i think i'm in camp put it in the footer. i dont agree it should be in the document. `header` or `footer` makes the most sense.
